# alembic/script.py.mako
"""initial schema

Revision ID: 08bff6ade262
Revises: 
Create Date: 2026-05-16 20:39:25.443349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08bff6ade262'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_pedido',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('forma_pago',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ingrediente',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('es_alergeno', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('unidad_medida',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('simbolo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('simbolo')
    )
    op.create_table('usuario',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('password_hash', sa.CHAR(length=60), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('direccion_entrega',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('linea1', sa.Text(), nullable=False),
    sa.Column('linea2', sa.Text(), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('imagenes_url', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('stock_cantidad', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('unidad_venta_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('precio_base >= 0', name='check_precio_base_positivo'),
    sa.CheckConstraint('stock_cantidad >= 0', name='check_stock_cantidad_positivo'),
    sa.ForeignKeyConstraint(['unidad_venta_id'], ['unidad_medida.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('rol_codigo', sa.String(length=20), nullable=False),
    sa.Column('asignado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['rol_codigo'], ['rol.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_codigo')
    )
    op.create_table('pedido',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_codigo', sa.String(length=20), nullable=False),
    sa.Column('forma_pago_codigo', sa.String(length=20), nullable=False),
    sa.Column('direccion_id', sa.BigInteger(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_envio', sa.DECIMAL(precision=10, scale=2), server_default='50.00', nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('total >= 0', name='check_total_positivo'),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion_entrega.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estado_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['forma_pago_codigo'], ['forma_pago.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_categoria',
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('categoria_id', sa.BigInteger(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('producto_ingrediente',
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('ingrediente_id', sa.BigInteger(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('unidad_medida_id', sa.BigInteger(), nullable=False),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id')
    )
    op.create_table('detalle_pedido',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=True),
    sa.Column('nombre_snapshot', sa.String(length=200), nullable=False),
    sa.Column('precio_snapshot', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_snap', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.SmallInteger(), nullable=False),
    sa.Column('personalizacion', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.CheckConstraint('cantidad >= 1', name='check_cantidad_minima'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_estado_pedido',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_desde', sa.String(length=20), nullable=True),
    sa.Column('estado_hasta', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_desde'], ['estado_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['estado_hasta'], ['estado_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('mp_payment_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_method_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('mp_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('mp_status_detail', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('mp_payment_id'),
    sa.UniqueConstraint('pedido_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('historial_estado_pedido')
    op.drop_table('detalle_pedido')
    op.drop_table('producto_ingrediente')
    op.drop_table('producto_categoria')
    op.drop_table('pedido')
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('producto')
    op.drop_table('direccion_entrega')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('unidad_medida')
    op.drop_table('rol')
    op.drop_table('ingrediente')
    op.drop_table('forma_pago')
    op.drop_table('estado_pedido')
    op.drop_table('categoria')
    # ### end Alembic commands ###